/*-------------------------------------------------------------------------
 *
 * kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef KWLIST_D_H
#define KWLIST_D_H

#include "parser/kwlookup.h"

static const char ScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"account\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"algorithm\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"app\0"
	"append\0"
	"apply\0"
	"archive\0"
	"array\0"
	"as\0"
	"asc\0"
	"asof\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"attribute\0"
	"audit\0"
	"authid\0"
	"authorization\0"
	"auto_increment\0"
	"autoextend\0"
	"automapped\0"
	"backward\0"
	"barrier\0"
	"before\0"
	"begin\0"
	"begin_non_anoyblock\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_double_infinity\0"
	"binary_double_nan\0"
	"binary_integer\0"
	"bit\0"
	"blanks\0"
	"blob\0"
	"blockchain\0"
	"body\0"
	"boolean\0"
	"both\0"
	"bucketcnt\0"
	"buckets\0"
	"build\0"
	"by\0"
	"byte\0"
	"byteawithoutorder\0"
	"byteawithoutorderwithequal\0"
	"cache\0"
	"call\0"
	"called\0"
	"cancelable\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"catalog_name\0"
	"chain\0"
	"change\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"characterset\0"
	"charset\0"
	"check\0"
	"checkpoint\0"
	"class\0"
	"class_origin\0"
	"clean\0"
	"client\0"
	"client_master_key\0"
	"client_master_keys\0"
	"clob\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"column_encryption_key\0"
	"column_encryption_keys\0"
	"column_name\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compact\0"
	"compatible_illegal_chars\0"
	"compile\0"
	"complete\0"
	"completion\0"
	"compress\0"
	"concurrently\0"
	"condition\0"
	"configuration\0"
	"connect\0"
	"connection\0"
	"consistent\0"
	"constant\0"
	"constraint\0"
	"constraint_catalog\0"
	"constraint_name\0"
	"constraint_schema\0"
	"constraints\0"
	"constructor\0"
	"content\0"
	"continue\0"
	"contview\0"
	"conversion\0"
	"convert\0"
	"coordinator\0"
	"coordinators\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csn\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cursor_name\0"
	"cycle\0"
	"data\0"
	"database\0"
	"datafile\0"
	"datanode\0"
	"datanodes\0"
	"datatype_cl\0"
	"date\0"
	"date_format\0"
	"day\0"
	"day_hour\0"
	"day_minute\0"
	"day_second\0"
	"dbcompatibility\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"delta\0"
	"deltamerge\0"
	"dense_rank\0"
	"desc\0"
	"deterministic\0"
	"diagnostics\0"
	"dictionary\0"
	"direct\0"
	"directory\0"
	"disable\0"
	"discard\0"
	"disconnect\0"
	"distinct\0"
	"distribute\0"
	"distribution\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"dumpfile\0"
	"duplicate\0"
	"each\0"
	"elastic\0"
	"else\0"
	"enable\0"
	"enclosed\0"
	"encoding\0"
	"encrypted\0"
	"encrypted_value\0"
	"encryption\0"
	"encryption_type\0"
	"end\0"
	"ends\0"
	"enforced\0"
	"enum\0"
	"eol\0"
	"error\0"
	"errors\0"
	"escape\0"
	"escaped\0"
	"escaping\0"
	"event\0"
	"events\0"
	"every\0"
	"except\0"
	"exchange\0"
	"exclude\0"
	"excluded\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"expired\0"
	"explain\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fast\0"
	"features\0"
	"fenced\0"
	"fetch\0"
	"fields\0"
	"fileheader\0"
	"fill_missing_fields\0"
	"filler\0"
	"filter\0"
	"final\0"
	"first\0"
	"fixed\0"
	"float\0"
	"following\0"
	"follows\0"
	"for\0"
	"force\0"
	"foreign\0"
	"formatter\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"get\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groupparent\0"
	"handler\0"
	"having\0"
	"hdfsdirectory\0"
	"header\0"
	"hold\0"
	"hour\0"
	"hour_minute\0"
	"hour_second\0"
	"identified\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ignore_extra_data\0"
	"ilike\0"
	"imcstored\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"incremental\0"
	"index\0"
	"indexes\0"
	"infile\0"
	"infinite\0"
	"inherit\0"
	"inherits\0"
	"initial\0"
	"initially\0"
	"initrans\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"internal\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"ip\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"join\0"
	"json_exists\0"
	"keep\0"
	"key\0"
	"key_path\0"
	"key_store\0"
	"kill\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"lc_collate\0"
	"lc_ctype\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"less\0"
	"level\0"
	"like\0"
	"limit\0"
	"lines\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"log\0"
	"logging\0"
	"login_any\0"
	"login_failure\0"
	"login_success\0"
	"logout\0"
	"long\0"
	"loop\0"
	"map\0"
	"mapping\0"
	"masking\0"
	"master\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"maxextents\0"
	"maxsize\0"
	"maxtrans\0"
	"maxvalue\0"
	"member\0"
	"merge\0"
	"message_text\0"
	"method\0"
	"minextents\0"
	"minus\0"
	"minute\0"
	"minute_second\0"
	"minvalue\0"
	"mode\0"
	"model\0"
	"modify\0"
	"month\0"
	"move\0"
	"movement\0"
	"mysql_errno\0"
	"name\0"
	"names\0"
	"nan\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"next\0"
	"no\0"
	"nocompress\0"
	"nocycle\0"
	"node\0"
	"nologging\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"none\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"novalidate\0"
	"nowait\0"
	"nth_value\0"
	"null\0"
	"nullcols\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"numstr\0"
	"nvarchar\0"
	"nvarchar2\0"
	"nvl\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"on\0"
	"only\0"
	"operator\0"
	"optimization\0"
	"option\0"
	"optionally\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"out\0"
	"outer\0"
	"outfile\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"owned\0"
	"owner\0"
	"package\0"
	"packages\0"
	"parallel_enable\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"pctfree\0"
	"per\0"
	"percent\0"
	"performance\0"
	"perm\0"
	"pipelined\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"pool\0"
	"position\0"
	"precedes\0"
	"preceding\0"
	"precision\0"
	"predict\0"
	"preferred\0"
	"prefix\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"priorer\0"
	"private\0"
	"privilege\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"profile\0"
	"publication\0"
	"publish\0"
	"purge\0"
	"query\0"
	"quote\0"
	"randomized\0"
	"range\0"
	"ratio\0"
	"raw\0"
	"read\0"
	"real\0"
	"reassign\0"
	"rebuild\0"
	"recheck\0"
	"recursive\0"
	"recyclebin\0"
	"redisanyvalue\0"
	"ref\0"
	"references\0"
	"refresh\0"
	"reindex\0"
	"reject\0"
	"relative\0"
	"release\0"
	"reloptions\0"
	"remote\0"
	"remove\0"
	"rename\0"
	"repeat\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"resize\0"
	"resource\0"
	"respect\0"
	"restart\0"
	"restrict\0"
	"result\0"
	"result_cache\0"
	"return\0"
	"returned_sqlstate\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"roles\0"
	"rollback\0"
	"rollup\0"
	"rotate\0"
	"rotation\0"
	"row\0"
	"row_count\0"
	"rownum\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"sample\0"
	"savepoint\0"
	"schedule\0"
	"schema\0"
	"schema_name\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"self\0"
	"separator\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"share_memory\0"
	"shippable\0"
	"show\0"
	"shrink\0"
	"shutdown\0"
	"siblings\0"
	"similar\0"
	"simple\0"
	"size\0"
	"skip\0"
	"slave\0"
	"slice\0"
	"smalldatetime\0"
	"smalldatetime_format\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"space\0"
	"specification\0"
	"spill\0"
	"split\0"
	"sql\0"
	"stable\0"
	"stacked\0"
	"standalone\0"
	"start\0"
	"starting\0"
	"starts\0"
	"statement\0"
	"statement_id\0"
	"static\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"store\0"
	"stored\0"
	"stratify\0"
	"stream\0"
	"strict\0"
	"strip\0"
	"subclass_origin\0"
	"subpartition\0"
	"subpartitions\0"
	"subscription\0"
	"substring\0"
	"symmetric\0"
	"synonym\0"
	"sys_refcursor\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"table\0"
	"table_name\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"terminated\0"
	"text\0"
	"than\0"
	"then\0"
	"ties\0"
	"time\0"
	"time_format\0"
	"timecapsule\0"
	"timestamp\0"
	"timestamp_format\0"
	"timestampdiff\0"
	"timezone_hour\0"
	"timezone_minute\0"
	"tinyint\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"tsfield\0"
	"tstag\0"
	"tstime\0"
	"type\0"
	"types\0"
	"unbounded\0"
	"uncommitted\0"
	"under\0"
	"unencrypted\0"
	"unimcstored\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlimited\0"
	"unlisten\0"
	"unlock\0"
	"unlogged\0"
	"until\0"
	"unusable\0"
	"update\0"
	"use\0"
	"useeof\0"
	"user\0"
	"using\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validation\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variables\0"
	"variadic\0"
	"varray\0"
	"varying\0"
	"vcgroup\0"
	"verbose\0"
	"verify\0"
	"version\0"
	"view\0"
	"visible\0"
	"volatile\0"
	"wait\0"
	"warnings\0"
	"weak\0"
	"when\0"
	"where\0"
	"while\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"workload\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"year\0"
	"year_month\0"
	"yes\0"
	"zone";

static const uint16 ScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	30,
	37,
	41,
	47,
	53,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	123,
	130,
	136,
	144,
	150,
	153,
	157,
	162,
	172,
	183,
	194,
	197,
	207,
	213,
	220,
	234,
	249,
	260,
	271,
	280,
	288,
	295,
	301,
	321,
	329,
	336,
	343,
	357,
	380,
	398,
	413,
	417,
	424,
	429,
	440,
	445,
	453,
	458,
	468,
	476,
	482,
	485,
	490,
	508,
	535,
	541,
	546,
	553,
	564,
	572,
	581,
	586,
	591,
	599,
	612,
	618,
	625,
	630,
	640,
	656,
	669,
	677,
	683,
	694,
	700,
	713,
	719,
	726,
	744,
	763,
	768,
	774,
	782,
	791,
	799,
	809,
	816,
	838,
	861,
	873,
	881,
	889,
	898,
	905,
	915,
	923,
	948,
	956,
	965,
	976,
	985,
	998,
	1008,
	1022,
	1030,
	1041,
	1052,
	1061,
	1072,
	1091,
	1107,
	1125,
	1137,
	1149,
	1157,
	1166,
	1175,
	1186,
	1194,
	1206,
	1219,
	1224,
	1229,
	1236,
	1242,
	1246,
	1250,
	1255,
	1263,
	1279,
	1292,
	1305,
	1320,
	1333,
	1351,
	1364,
	1371,
	1383,
	1389,
	1394,
	1403,
	1412,
	1421,
	1431,
	1443,
	1448,
	1460,
	1464,
	1473,
	1484,
	1495,
	1511,
	1522,
	1526,
	1534,
	1542,
	1549,
	1557,
	1566,
	1577,
	1586,
	1594,
	1601,
	1611,
	1622,
	1628,
	1639,
	1650,
	1655,
	1669,
	1681,
	1692,
	1699,
	1709,
	1717,
	1725,
	1736,
	1745,
	1756,
	1769,
	1772,
	1781,
	1788,
	1795,
	1800,
	1809,
	1819,
	1824,
	1832,
	1837,
	1844,
	1853,
	1862,
	1872,
	1888,
	1899,
	1915,
	1919,
	1924,
	1933,
	1938,
	1942,
	1948,
	1955,
	1962,
	1970,
	1979,
	1985,
	1992,
	1998,
	2005,
	2014,
	2022,
	2031,
	2041,
	2051,
	2059,
	2066,
	2074,
	2082,
	2092,
	2101,
	2109,
	2115,
	2122,
	2127,
	2136,
	2143,
	2149,
	2156,
	2167,
	2187,
	2194,
	2201,
	2207,
	2213,
	2219,
	2225,
	2235,
	2243,
	2247,
	2253,
	2261,
	2271,
	2279,
	2286,
	2291,
	2296,
	2305,
	2315,
	2325,
	2329,
	2336,
	2342,
	2350,
	2359,
	2365,
	2374,
	2386,
	2394,
	2401,
	2415,
	2422,
	2427,
	2432,
	2444,
	2456,
	2467,
	2476,
	2479,
	2486,
	2504,
	2510,
	2520,
	2530,
	2540,
	2549,
	2552,
	2560,
	2570,
	2580,
	2592,
	2598,
	2606,
	2613,
	2622,
	2630,
	2639,
	2647,
	2657,
	2666,
	2673,
	2679,
	2685,
	2691,
	2703,
	2710,
	2718,
	2722,
	2730,
	2739,
	2749,
	2758,
	2763,
	2773,
	2781,
	2784,
	2787,
	2794,
	2804,
	2809,
	2821,
	2826,
	2830,
	2839,
	2849,
	2854,
	2860,
	2869,
	2875,
	2880,
	2888,
	2899,
	2908,
	2916,
	2926,
	2932,
	2937,
	2942,
	2948,
	2953,
	2959,
	2965,
	2970,
	2977,
	2982,
	2988,
	2998,
	3013,
	3022,
	3027,
	3034,
	3038,
	3046,
	3056,
	3070,
	3084,
	3091,
	3096,
	3101,
	3105,
	3113,
	3121,
	3128,
	3134,
	3142,
	3155,
	3166,
	3174,
	3183,
	3192,
	3199,
	3205,
	3218,
	3225,
	3236,
	3242,
	3249,
	3263,
	3272,
	3277,
	3283,
	3290,
	3296,
	3301,
	3310,
	3322,
	3327,
	3333,
	3337,
	3346,
	3354,
	3360,
	3365,
	3368,
	3379,
	3387,
	3392,
	3402,
	3413,
	3424,
	3429,
	3433,
	3441,
	3448,
	3456,
	3467,
	3474,
	3484,
	3489,
	3498,
	3505,
	3511,
	3518,
	3526,
	3533,
	3542,
	3552,
	3556,
	3563,
	3566,
	3570,
	3577,
	3582,
	3585,
	3590,
	3599,
	3612,
	3619,
	3630,
	3638,
	3641,
	3647,
	3658,
	3662,
	3668,
	3676,
	3681,
	3690,
	3698,
	3704,
	3710,
	3718,
	3727,
	3743,
	3750,
	3758,
	3768,
	3779,
	3787,
	3796,
	3804,
	3808,
	3816,
	3828,
	3833,
	3843,
	3851,
	3856,
	3862,
	3869,
	3874,
	3883,
	3892,
	3902,
	3912,
	3920,
	3930,
	3937,
	3945,
	3954,
	3963,
	3971,
	3977,
	3985,
	3993,
	4003,
	4014,
	4025,
	4035,
	4043,
	4055,
	4063,
	4069,
	4075,
	4081,
	4092,
	4098,
	4104,
	4108,
	4113,
	4118,
	4127,
	4135,
	4143,
	4153,
	4164,
	4178,
	4182,
	4193,
	4201,
	4209,
	4216,
	4225,
	4233,
	4244,
	4251,
	4258,
	4265,
	4272,
	4283,
	4291,
	4299,
	4305,
	4312,
	4321,
	4329,
	4337,
	4346,
	4353,
	4366,
	4373,
	4391,
	4401,
	4409,
	4415,
	4422,
	4428,
	4433,
	4439,
	4448,
	4455,
	4462,
	4471,
	4475,
	4485,
	4492,
	4497,
	4505,
	4510,
	4517,
	4527,
	4536,
	4543,
	4555,
	4562,
	4569,
	4576,
	4585,
	4592,
	4597,
	4607,
	4616,
	4626,
	4639,
	4646,
	4654,
	4667,
	4671,
	4677,
	4682,
	4688,
	4701,
	4711,
	4716,
	4723,
	4732,
	4741,
	4749,
	4756,
	4761,
	4766,
	4772,
	4778,
	4792,
	4813,
	4822,
	4831,
	4836,
	4843,
	4849,
	4863,
	4869,
	4875,
	4879,
	4886,
	4894,
	4905,
	4911,
	4920,
	4927,
	4937,
	4950,
	4957,
	4968,
	4974,
	4981,
	4989,
	4995,
	5002,
	5011,
	5018,
	5025,
	5031,
	5047,
	5060,
	5074,
	5087,
	5097,
	5107,
	5115,
	5129,
	5137,
	5143,
	5150,
	5156,
	5167,
	5174,
	5186,
	5197,
	5204,
	5209,
	5218,
	5228,
	5239,
	5244,
	5249,
	5254,
	5259,
	5264,
	5276,
	5288,
	5298,
	5315,
	5329,
	5343,
	5359,
	5367,
	5370,
	5379,
	5391,
	5401,
	5407,
	5415,
	5420,
	5425,
	5434,
	5442,
	5450,
	5456,
	5463,
	5468,
	5474,
	5484,
	5496,
	5502,
	5514,
	5526,
	5532,
	5539,
	5547,
	5557,
	5566,
	5573,
	5582,
	5588,
	5597,
	5604,
	5608,
	5615,
	5620,
	5626,
	5633,
	5639,
	5648,
	5659,
	5669,
	5675,
	5682,
	5690,
	5699,
	5709,
	5718,
	5725,
	5733,
	5741,
	5749,
	5756,
	5764,
	5769,
	5777,
	5786,
	5791,
	5800,
	5805,
	5810,
	5816,
	5822,
	5833,
	5840,
	5845,
	5852,
	5860,
	5865,
	5874,
	5882,
	5888,
	5892,
	5906,
	5916,
	5927,
	5937,
	5947,
	5961,
	5970,
	5976,
	5984,
	5997,
	6006,
	6011,
	6022,
	6026,
};

#define SCANKEYWORDS_NUM_KEYWORDS 721

static int
ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1443] = {
		32767, -495,  555,   32767, 0,     32767, 460,   -657,
		584,   -600,  -89,   0,     0,     32767, 142,   32767,
		416,   429,   902,   0,     32767, 32767, 0,     32767,
		32767, 32767, 57,    0,     -12,   -235,  32767, -1325,
		0,     680,   -632,  802,   32767, 32767, 32767, 32767,
		1114,  32767, 31,    -39,   0,     411,   -347,  32767,
		32767, 32767, 479,   32767, 32767, 0,     187,   -101,
		293,   166,   -547,  -160,  32767, 679,   0,     558,
		20,    0,     -443,  32767, 268,   -282,  0,     32767,
		32767, 409,   -64,   -17,   32767, 0,     1013,  32767,
		104,   0,     456,   0,     401,   32767, 584,   167,
		27,    795,   32767, 32767, 356,   465,   32767, 32767,
		402,   496,   32767, 32767, 1054,  215,   32767, 32767,
		287,   32767, 567,   32767, 164,   597,   19,    32767,
		32767, 958,   -287,  271,   291,   32767, 32767, 284,
		19,    483,   32767, -159,  402,   202,   0,     0,
		-267,  371,   -386,  858,   696,   32767, -51,   493,
		67,    32767, 32767, 1022,  32767, 0,     369,   -140,
		-188,  568,   62,    32767, 0,     27,    32767, 455,
		449,   32767, 529,   181,   375,   -436,  776,   -1000,
		32767, 32767, 0,     700,   937,   -356,  32767, 32767,
		221,   540,   508,   32767, 43,    32767, 0,     -129,
		32767, 601,   32767, 231,   144,   462,   558,   -191,
		-188,  705,   32767, 230,   -538,  -243,  -360,  -268,
		32767, 346,   526,   -156,  282,   32767, 281,   32767,
		898,   32767, 334,   32767, 277,   0,     32767, 989,
		32767, 0,     404,   32767, 32767, 32767, 0,     571,
		32767, 709,   0,     -526,  56,    699,   32767, 32767,
		-48,   32767, 695,   32767, 32767, 32767, 579,   32767,
		32767, 32767, -236,  0,     572,   238,   32767, 177,
		566,   32767, 32767, 320,   32767, 32767, 32767, 32767,
		32767, 128,   808,   0,     0,     32767, 32767, 32767,
		54,    351,   0,     0,     32767, 32767, 32767, 32767,
		32767, 83,    -1065, 224,   32767, 0,     0,     32767,
		-424,  32767, 659,   483,   334,   -985,  -81,   32767,
		10,    32767, -425,  498,   0,     1106,  634,   996,
		-400,  32767, 966,   32767, 385,   32767, 32767, -571,
		783,   308,   671,   76,    0,     -96,   32767, 0,
		258,   -347,  -137,  605,   0,     32767, 312,   0,
		32767, 244,   938,   32767, 32767, 34,    32767, 32767,
		32767, 0,     32767, 22,    678,   660,   157,   0,
		-32,   -34,   0,     32767, 32767, 630,   0,     -454,
		340,   13,    -194,  32767, 347,   -163,  32767, -891,
		470,   32767, 0,     133,   727,   431,   -353,  0,
		26,    32767, 0,     0,     32767, 587,   -426,  -31,
		32767, 32767, 971,   689,   32767, -233,  -464,  639,
		560,   32767, 428,   229,   0,     394,   32767, -298,
		464,   32767, -234,  269,   -329,  -341,  -175,  32767,
		-5,    0,     0,     32767, 0,     601,   32767, 322,
		0,     267,   32767, 32767, -312,  87,    32767, -94,
		-232,  493,   677,   439,   88,    618,   964,   32767,
		212,   1839,  111,   489,   32767, -315,  32767, 629,
		634,   -391,  165,   32767, 32767, 32767, -546,  32767,
		32767, 32767, 32767, 32767, 28,    -476,  0,     137,
		319,   1193,  340,   -396,  -143,  118,   78,    32767,
		-502,  39,    32767, 32767, -1264, 32767, 13,    32767,
		32767, 32767, 32767, 32767, 102,   40,    32767, 14,
		32767, 660,   -114,  430,   32767, 32767, 32767, 130,
		32767, 32767, -258,  0,     -423,  268,   531,   -5,
		442,   215,   32767, 281,   32767, 0,     341,   32767,
		32767, 32767, -260,  32767, 599,   598,   32767, 721,
		32767, 32767, 494,   32767, 32767, 130,   -64,   549,
		32767, -34,   32767, 32767, 363,   -193,  427,   32767,
		0,     32767, 320,   32767, 480,   32767, 0,     32767,
		563,   304,   -165,  32767, 32767, 32767, 32767, 797,
		32767, 32767, -67,   32767, 32767, 0,     32767, 32767,
		544,   -174,  32767, 32767, 318,   -138,  0,     32767,
		559,   32767, 32767, 32767, 32767, 32767, -92,   -13,
		32767, 0,     32767, 359,   32767, 0,     32767, 1187,
		32767, -290,  85,    118,   32767, 976,   757,   32767,
		32767, 332,   -281,  32767, 32767, 32767, 214,   0,
		32767, 0,     32767, -460,  32767, 0,     32767, 32767,
		32767, 86,    568,   32767, 32767, 317,   408,   32767,
		32767, 748,   32767, 0,     88,    0,     32767, 619,
		458,   32767, 24,    32767, 0,     106,   32767, 32767,
		667,   0,     32767, 32767, 62,    32767, -321,  1807,
		0,     937,   -281,  194,   0,     175,   201,   817,
		32767, 32767, -1359, 704,   -363,  470,   -52,   32767,
		213,   0,     220,   -536,  715,   32767, 32767, 49,
		196,   -255,  32767, 32767, 601,   32767, 0,     595,
		286,   32767, 187,   32767, 32767, 32767, 33,    32767,
		-141,  662,   32767, 376,   672,   716,   591,   676,
		-94,   -622,  -346,  32767, 582,   32767, 116,   -121,
		0,     -222,  661,   0,     489,   32767, 195,   32767,
		32767, 32767, -237,  32767, 477,   32767, 32767, 330,
		1101,  0,     192,   648,   32767, 0,     549,   28,
		437,   -27,   344,   32767, 32767, 719,   32767, 32767,
		490,   645,   0,     32767, 538,   47,    32767, 354,
		0,     32767, 32767, 627,   32767, -270,  32767, 32767,
		32767, 0,     0,     32767, 32767, 0,     -649,  -381,
		-59,   32767, 32767, 32767, 980,   69,    70,    858,
		32767, 32767, 0,     0,     32767, 343,   380,   0,
		32767, 32767, 32767, 371,   70,    411,   32767, 578,
		-610,  810,   260,   32767, 32767, 109,   344,   0,
		512,   32767, 61,    32767, 32767, 32767, -368,  32767,
		32767, 708,   0,     656,   60,    32767, 520,   -5,
		-328,  32767, 32767, 32767, 363,   32767, 32767, 32767,
		314,   253,   -87,   -367,  32767, 745,   541,   69,
		763,   32767, 16,    32767, 602,   595,   488,   1184,
		64,    32767, 32767, 32767, 32767, 8,     32767, 204,
		-872,  166,   -154,  0,     -13,   117,   32767, 364,
		149,   -379,  32767, 606,   -452,  32767, 617,   32767,
		32767, 327,   0,     -33,   197,   32767, 0,     -840,
		292,   -877,  32767, 0,     -16,   32767, 32767, 32767,
		32767, 0,     32767, 0,     221,   32767, 140,   149,
		32767, 403,   -84,   0,     181,   32767, 258,   624,
		0,     0,     32767, 32767, 0,     32767, 389,   214,
		32767, 32767, 73,    32767, 486,   0,     0,     0,
		334,   32767, -103,  546,   32767, 239,   32767, -278,
		-524,  32767, 0,     32767, 222,   32767, 32767, 32767,
		32767, 365,   797,   495,   0,     -43,   32767, 32767,
		32767, 32767, 32767, 32767, 280,   -37,   -294,  32767,
		150,   401,   0,     575,   32767, -351,  32767, -194,
		194,   215,   32767, 32767, -693,  348,   32767, 593,
		-409,  123,   1203,  408,   179,   58,    156,   373,
		32767, 84,    0,     0,     0,     0,     32767, 36,
		181,   -813,  -423,  0,     32767, 32767, 32767, 32767,
		1065,  0,     32767, 1003,  -415,  32767, 32767, -331,
		120,   32767, -604,  -92,   815,   471,   0,     6,
		32767, 658,   0,     0,     139,   0,     32767, 313,
		32767, -168,  530,   32767, 392,   0,     32767, 364,
		32767, -421,  32767, 32767, 108,   703,   32767, 0,
		-54,   633,   32767, 0,     596,   384,   0,     74,
		562,   32767, 349,   311,   187,   330,   186,   32767,
		280,   629,   71,    32767, 32767, -68,   243,   0,
		312,   32767, 0,     32767, 524,   585,   553,   32767,
		32767, 272,   32767, 32767, 32767, 32767, -397,  32767,
		32767, 233,   32767, 32767, -281,  678,   0,     32767,
		75,    195,   518,   32767, 0,     32767, 32767, 229,
		32767, 32767, 32767, 665,   477,   32767, 0,     596,
		-400,  145,   32767, 32767, -50,   547,   416,   0,
		1383,  -447,  32767, 720,   61,    508,   32767, 771,
		306,   32767, 0,     319,   32767, 32767, 32767, 1449,
		32767, 1623,  32767, 436,   0,     32767, -298,  -358,
		32767, 784,   583,   420,   32767, 690,   237,   0,
		661,   32767, 0,     32767, 425,   0,     32767, 32767,
		32767, 32767, 32767, 32767, 0,     240,   32767, -35,
		248,   32767, -591,  32767, 32767, 32767, 292,   0,
		0,     407,   1184,  32767, 0,     0,     0,     400,
		-187,  -66,   32767, 364,   331,   32767, -57,   32767,
		32767, -126,  -603,  -264,  0,     468,   55,    32767,
		-273,  32767, 32767, 693,   600,   1224,  32767, 32767,
		0,     554,   0,     32767, -11,   32767, 32767, -647,
		33,    481,   325,   122,   32767, -493,  0,     32767,
		0,     508,   0,     175,   32767, 32767, 32767, 32767,
		197,   32767, 831,   32767, 32767, 32767, 32767, 0,
		32767, 0,     0,     32767, -677,  32767, 32767, 0,
		-355,  484,   209,   32767, 32767, 32767, 244,   548,
		32767, 0,     492,   -373,  0,     32767, 32767, 32767,
		-534,  463,   162,   0,     405,   426,   32767, 32767,
		0,     32767, -540,  32767, 32767, 32767, 32767, 32767,
		32767, 32767, 32767, 635,   418,   32767, 32767, 32767,
		582,   32767, 32767, 768,   422,   32767, 32767, 647,
		-195,  837,   32767, 0,     152,   0,     32767, 337,
		32767, -143,  717,   32767, 0,     0,     32767, 311,
		32767, 338,   1156,  32767, 631,   114,   0,     459,
		815,   -61,   0,     0,     0,     32767, 32767, 0,
		32767, 0,     459,   611,   807,   218,   0,     -437,
		900,   115,   -463,  32767, -168,  588,   32767, 590,
		32767, 32767, 655,   597,   433,   725,   385,   32767,
		810,   32767, 32767, 32767, 32767, 653,   387,   195,
		0,     32767, 555,   32767, -174,  160,   32767, 32767,
		32767, 0,     32767, 0,     32767, 32767, 32767, 32767,
		498,   32767, 145,   -124,  260,   32767, 0,     650,
		18,    32767, 32767, 0,     32767, -339,  492,   32767,
		413,   172,   32767, 0,     32767, 32767, -320,  -1101,
		376,   -302,  306,   359,   0,     32767, 3,     0,
		-37,   32767, 32767, 475,   478,   419,   0,     0,
		0,     32767, 32767, -161,  298,   -1126, 682,   32767,
		32767, -123,  6,     711,   32767, -158,  32767, 0,
		0,     391,   32767, 0,     415,   216,   0,     -576,
		32767, 178,   32767, 698,   663,   22,    0,     318,
		32767, 330,   0,     192,   594,   0,     0,     0,
		32767, 124,   590,   542,   651,   32767, 32767, 205,
		32767, 447,   32767, 32767, 32767, 32767, 32767, 0,
		32767, -129,  227,   0,     32767, 1167,  32767, 6,
		557,   0,     -94,   98,    441,   0,     32767, 0,
		223,   0,     -661,  0,     501,   0,     32767, 133,
		686,   32767, 32767, 0,     501,   32767, 32767, 134,
		199,   0,     176,   32767, -60,   0,     0,     0,
		82,    32767, 673
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 1;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 17 + c;
	}
	return h[a % 1443] + h[b % 1443];
}

const ScanKeywordList ScanKeywords = {
	ScanKeywords_kw_string,
	ScanKeywords_kw_offsets,
	ScanKeywords_hash_func,
	SCANKEYWORDS_NUM_KEYWORDS,
	26
};

#endif							/* KWLIST_D_H */
