/*-------------------------------------------------------------------------
 *
 * pl_reserved_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef PL_RESERVED_KWLIST_D_H
#define PL_RESERVED_KWLIST_D_H

#include "parser/kwlookup.h"

static const char ReservedPLKeywords_kw_string[] =
	"all\0"
	"begin\0"
	"by\0"
	"case\0"
	"catch\0"
	"close\0"
	"collate\0"
	"declare\0"
	"default\0"
	"delete\0"
	"diagnostics\0"
	"else\0"
	"elseif\0"
	"elsif\0"
	"end\0"
	"exception\0"
	"exec\0"
	"execute\0"
	"exit\0"
	"fetch\0"
	"for\0"
	"forall\0"
	"foreach\0"
	"from\0"
	"function\0"
	"get\0"
	"goto\0"
	"if\0"
	"in\0"
	"insert\0"
	"into\0"
	"limit\0"
	"loop\0"
	"move\0"
	"not\0"
	"null\0"
	"of\0"
	"open\0"
	"or\0"
	"out\0"
	"procedure\0"
	"raise\0"
	"ref\0"
	"return\0"
	"select\0"
	"strict\0"
	"then\0"
	"to\0"
	"try\0"
	"update\0"
	"using\0"
	"when\0"
	"while";

static const uint16 ReservedPLKeywords_kw_offsets[] = {
	0,
	4,
	10,
	13,
	18,
	24,
	30,
	38,
	46,
	54,
	61,
	73,
	78,
	85,
	91,
	95,
	105,
	110,
	118,
	123,
	129,
	133,
	140,
	148,
	153,
	162,
	166,
	171,
	174,
	177,
	184,
	189,
	195,
	200,
	205,
	209,
	214,
	217,
	222,
	225,
	229,
	239,
	245,
	249,
	256,
	263,
	270,
	275,
	278,
	282,
	289,
	295,
	300,
};

#define RESERVEDPLKEYWORDS_NUM_KEYWORDS 53

static int
ReservedPLKeywords_hash_func(const void *key, size_t keylen)
{
	static const int8 h[107] = {
		127,   127,   127,   127,   -61,   127,   28,    65,
		0,     -26,   127,   19,    -10,   127,   0,     127,
		8,     127,   127,   127,   22,    25,    127,   12,
		14,    1,     9,     69,    36,    20,    17,    104,
		127,   23,    127,   44,    0,     0,     34,    127,
		127,   19,    127,   -25,   127,   127,   127,   24,
		11,    14,    -21,   41,    29,    0,     31,    -38,
		127,   0,     127,   35,    0,     29,    127,   31,
		33,    -40,   127,   -9,    0,     127,   47,    127,
		38,    -28,   36,    40,    0,     127,   127,   0,
		127,   -52,   4,     127,   127,   127,   0,     127,
		16,    21,    11,    127,   0,     127,   49,    45,
		0,     -8,    14,    -13,   127,   5,     127,   127,
		127,   127,   127
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 1;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 8191 + c;
	}
	return h[a % 107] + h[b % 107];
}

static const ScanKeywordList ReservedPLKeywords = {
	ReservedPLKeywords_kw_string,
	ReservedPLKeywords_kw_offsets,
	ReservedPLKeywords_hash_func,
	RESERVEDPLKEYWORDS_NUM_KEYWORDS,
	11
};

#endif							/* PL_RESERVED_KWLIST_D_H */
