/*-------------------------------------------------------------------------
 *
 * pl_unreserved_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef PL_UNRESERVED_KWLIST_D_H
#define PL_UNRESERVED_KWLIST_D_H

#include "parser/kwlookup.h"

static const char UnreservedPLKeywords_kw_string[] =
	"absolute\0"
	"alias\0"
	"alter\0"
	"array\0"
	"as\0"
	"backward\0"
	"bulk\0"
	"call\0"
	"catalog_name\0"
	"class_origin\0"
	"collect\0"
	"column_name\0"
	"commit\0"
	"condition\0"
	"constant\0"
	"constraint_catalog\0"
	"constraint_name\0"
	"constraint_schema\0"
	"continue\0"
	"current\0"
	"cursor\0"
	"cursor_name\0"
	"debug\0"
	"detail\0"
	"distinct\0"
	"do\0"
	"dump\0"
	"errcode\0"
	"error\0"
	"except\0"
	"exceptions\0"
	"false\0"
	"first\0"
	"forward\0"
	"found\0"
	"function\0"
	"handler\0"
	"hint\0"
	"immediate\0"
	"index\0"
	"info\0"
	"instantiation\0"
	"intersect\0"
	"is\0"
	"iterate\0"
	"last\0"
	"leave\0"
	"log\0"
	"merge\0"
	"message\0"
	"message_text\0"
	"multiset\0"
	"mysql_errno\0"
	"next\0"
	"no\0"
	"notice\0"
	"number\0"
	"option\0"
	"package\0"
	"perform\0"
	"pg_exception_context\0"
	"pg_exception_detail\0"
	"pg_exception_hint\0"
	"pipe\0"
	"pragma\0"
	"prior\0"
	"procedure\0"
	"query\0"
	"record\0"
	"relative\0"
	"release\0"
	"repeat\0"
	"replace\0"
	"resignal\0"
	"result_oid\0"
	"returned_sqlstate\0"
	"reverse\0"
	"rollback\0"
	"row\0"
	"row_count\0"
	"rowtype\0"
	"save\0"
	"savepoint\0"
	"schema_name\0"
	"scroll\0"
	"signal\0"
	"slice\0"
	"sqlexception\0"
	"sqlstate\0"
	"sqlwarning\0"
	"stacked\0"
	"subclass_origin\0"
	"subtype\0"
	"sys_refcursor\0"
	"table\0"
	"table_name\0"
	"tran\0"
	"transaction\0"
	"true\0"
	"type\0"
	"union\0"
	"until\0"
	"use_column\0"
	"use_variable\0"
	"variable_conflict\0"
	"varray\0"
	"warning\0"
	"with";

static const uint16 UnreservedPLKeywords_kw_offsets[] = {
	0,
	9,
	15,
	21,
	27,
	30,
	39,
	44,
	49,
	62,
	75,
	83,
	95,
	102,
	112,
	121,
	140,
	156,
	174,
	183,
	191,
	198,
	210,
	216,
	223,
	232,
	235,
	240,
	248,
	254,
	261,
	272,
	278,
	284,
	292,
	298,
	307,
	315,
	320,
	330,
	336,
	341,
	355,
	365,
	368,
	376,
	381,
	387,
	391,
	397,
	405,
	418,
	427,
	439,
	444,
	447,
	454,
	461,
	468,
	476,
	484,
	505,
	525,
	543,
	548,
	555,
	561,
	571,
	577,
	584,
	593,
	601,
	608,
	616,
	625,
	636,
	654,
	662,
	671,
	675,
	685,
	693,
	698,
	708,
	720,
	727,
	734,
	740,
	753,
	762,
	773,
	781,
	797,
	805,
	819,
	825,
	836,
	841,
	853,
	858,
	863,
	869,
	875,
	886,
	899,
	917,
	924,
	932,
};

#define UNRESERVEDPLKEYWORDS_NUM_KEYWORDS 108

static int
UnreservedPLKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[217] = {
		-1,    11,    0,     32767, 32767, 32767, 19,    70,
		62,    32767, 32767, 32767, 32767, 32767, 0,     32767,
		65,    32767, -16,   -54,   32767, 32767, -133,  -6,
		32767, 66,    32767, 84,    1,     32767, 0,     32767,
		102,   32767, 32767, 32767, 32767, 32767, 42,    32767,
		3,     -158,  0,     -69,   0,     -12,   32767, 32767,
		32767, -50,   127,   -117,  32767, -35,   23,    32767,
		13,    -26,   -72,   32767, 32767, 79,    86,    32767,
		0,     -36,   62,    0,     -14,   32767, 32767, 32767,
		32767, 12,    32767, 31,    89,    32,    32767, 32767,
		-77,   32767, 32767, 121,   82,    32767, 32767, 130,
		32767, 40,    38,    5,     32767, 83,    32767, 75,
		32767, 76,    -45,   19,    32767, 32767, 32767, 81,
		32767, 0,     32767, 29,    28,    151,   32767, 32767,
		32767, 53,    32767, 0,     32767, 32767, 32767, -34,
		-48,   32767, 1,     16,    31,    32767, 12,    32767,
		-2,    48,    39,    0,     32767, 102,   32767, 67,
		-98,   32767, 0,     -33,   32767, 32767, 32767, 20,
		125,   32767, 59,    0,     152,   41,    32767, 90,
		-105,  -4,    32767, 32767, -5,    0,     32767, 109,
		32767, 32767, 106,   86,    138,   32767, 73,    165,
		24,    0,     85,    -49,   34,    -57,   184,   10,
		77,    37,    32767, 32767, 107,   32767, 32767, -93,
		-3,    100,   0,     100,   -131,  32767, 32767, 93,
		-42,   103,   0,     0,     0,     32767, 32767, 32767,
		96,    136,   0,     32767, 32767, -37,   0,     32767,
		0,     0,     -29,   91,    82,    85,    114,   0,
		32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 217] + h[b % 217];
}

static const ScanKeywordList UnreservedPLKeywords = {
	UnreservedPLKeywords_kw_string,
	UnreservedPLKeywords_kw_offsets,
	UnreservedPLKeywords_hash_func,
	UNRESERVEDPLKEYWORDS_NUM_KEYWORDS,
	20
};

#endif							/* PL_UNRESERVED_KWLIST_D_H */
