/*-------------------------------------------------------------------------
 *
 * kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2019, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef KWLIST_D_H
#define KWLIST_D_H

#include "parser/kwlookup.h"

static const char pgtsql_ScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"account\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"algorithm\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"app\0"
	"append\0"
	"apply\0"
	"archive\0"
	"array\0"
	"as\0"
	"asc\0"
	"asof\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"attribute\0"
	"audit\0"
	"authid\0"
	"authorization\0"
	"auto_increment\0"
	"autoextend\0"
	"automapped\0"
	"backward\0"
	"barrier\0"
	"before\0"
	"begin\0"
	"begin_non_anoyblock\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"binary_double\0"
	"binary_double_infinity\0"
	"binary_double_nan\0"
	"binary_integer\0"
	"bit\0"
	"blanks\0"
	"blob\0"
	"blockchain\0"
	"body\0"
	"boolean\0"
	"both\0"
	"bucketcnt\0"
	"buckets\0"
	"build\0"
	"by\0"
	"byte\0"
	"byteawithoutorder\0"
	"byteawithoutorderwithequal\0"
	"cache\0"
	"call\0"
	"called\0"
	"cancelable\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"catalog_name\0"
	"catch\0"
	"chain\0"
	"change\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"characterset\0"
	"charset\0"
	"check\0"
	"checkident\0"
	"checkpoint\0"
	"class\0"
	"class_origin\0"
	"clean\0"
	"client\0"
	"client_master_key\0"
	"client_master_keys\0"
	"clob\0"
	"close\0"
	"cluster\0"
	"clustered\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"column_encryption_key\0"
	"column_encryption_keys\0"
	"column_name\0"
	"columns\0"
	"columnstore\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compact\0"
	"compatible_illegal_chars\0"
	"compile\0"
	"complete\0"
	"completion\0"
	"compress\0"
	"concurrently\0"
	"condition\0"
	"configuration\0"
	"connect\0"
	"connection\0"
	"consistent\0"
	"constant\0"
	"constraint\0"
	"constraint_catalog\0"
	"constraint_name\0"
	"constraint_schema\0"
	"constraints\0"
	"constructor\0"
	"content\0"
	"continue\0"
	"contview\0"
	"conversion\0"
	"convert\0"
	"coordinator\0"
	"coordinators\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csn\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cursor_name\0"
	"cycle\0"
	"d\0"
	"data\0"
	"database\0"
	"datafile\0"
	"datanode\0"
	"datanodes\0"
	"datatype_cl\0"
	"date\0"
	"date_format\0"
	"datediff\0"
	"datediff_big\0"
	"day\0"
	"day_hour\0"
	"day_minute\0"
	"day_second\0"
	"dayofyear\0"
	"dbcc\0"
	"dbcompatibility\0"
	"dd\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"decode\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"delta\0"
	"deltamerge\0"
	"dense_rank\0"
	"desc\0"
	"deterministic\0"
	"diagnostics\0"
	"dictionary\0"
	"direct\0"
	"directory\0"
	"disable\0"
	"discard\0"
	"disconnect\0"
	"distinct\0"
	"distribute\0"
	"distribution\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"dumpfile\0"
	"duplicate\0"
	"dw\0"
	"dy\0"
	"each\0"
	"elastic\0"
	"else\0"
	"enable\0"
	"enclosed\0"
	"encoding\0"
	"encrypted\0"
	"encrypted_value\0"
	"encryption\0"
	"encryption_type\0"
	"end\0"
	"ends\0"
	"enforced\0"
	"enum\0"
	"eol\0"
	"error\0"
	"errors\0"
	"escape\0"
	"escaped\0"
	"escaping\0"
	"event\0"
	"events\0"
	"every\0"
	"except\0"
	"exchange\0"
	"exclude\0"
	"excluded\0"
	"excluding\0"
	"exclusive\0"
	"exec\0"
	"execute\0"
	"exists\0"
	"expired\0"
	"explain\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fast\0"
	"features\0"
	"fenced\0"
	"fetch\0"
	"fields\0"
	"fileheader\0"
	"fill_missing_fields\0"
	"filler\0"
	"filter\0"
	"final\0"
	"first\0"
	"fixed\0"
	"float\0"
	"following\0"
	"follows\0"
	"for\0"
	"force\0"
	"foreign\0"
	"formatter\0"
	"forward\0"
	"freeze\0"
	"from\0"
	"full\0"
	"function\0"
	"functions\0"
	"generated\0"
	"get\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"grouping\0"
	"groupparent\0"
	"handler\0"
	"having\0"
	"hdfsdirectory\0"
	"header\0"
	"hh\0"
	"hold\0"
	"hour\0"
	"hour_minute\0"
	"hour_second\0"
	"identified\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ignore_extra_data\0"
	"ilike\0"
	"imcstored\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"incremental\0"
	"index\0"
	"indexes\0"
	"infile\0"
	"infinite\0"
	"inherit\0"
	"inherits\0"
	"initial\0"
	"initially\0"
	"initrans\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"instead\0"
	"int\0"
	"integer\0"
	"internal\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"ip\0"
	"is\0"
	"isnull\0"
	"isolation\0"
	"join\0"
	"json_exists\0"
	"keep\0"
	"key\0"
	"key_path\0"
	"key_store\0"
	"kill\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"lc_collate\0"
	"lc_ctype\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"left\0"
	"less\0"
	"level\0"
	"like\0"
	"limit\0"
	"lines\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"log\0"
	"logging\0"
	"login_any\0"
	"login_failure\0"
	"login_success\0"
	"logout\0"
	"loop\0"
	"m\0"
	"map\0"
	"mapping\0"
	"masking\0"
	"master\0"
	"match\0"
	"matched\0"
	"materialized\0"
	"max\0"
	"maxextents\0"
	"maxsize\0"
	"maxtrans\0"
	"maxvalue\0"
	"mcs\0"
	"member\0"
	"merge\0"
	"message_text\0"
	"method\0"
	"mi\0"
	"microsecond\0"
	"millisecond\0"
	"minextents\0"
	"minus\0"
	"minute\0"
	"minute_second\0"
	"minutes\0"
	"minvalue\0"
	"mm\0"
	"mode\0"
	"model\0"
	"modify\0"
	"month\0"
	"move\0"
	"movement\0"
	"ms\0"
	"mysql_errno\0"
	"n\0"
	"name\0"
	"names\0"
	"nan\0"
	"nanosecond\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"next\0"
	"no\0"
	"no_infomsgs\0"
	"nocompress\0"
	"nocycle\0"
	"node\0"
	"noexpand\0"
	"nolock\0"
	"nologging\0"
	"nomaxvalue\0"
	"nominvalue\0"
	"nonclustered\0"
	"none\0"
	"noreseed\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"novalidate\0"
	"nowait\0"
	"ns\0"
	"nth_value\0"
	"null\0"
	"nullcols\0"
	"nullif\0"
	"nulls\0"
	"number\0"
	"numeric\0"
	"numstr\0"
	"nvarchar\0"
	"nvarchar2\0"
	"nvl\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"on\0"
	"only\0"
	"operator\0"
	"optimization\0"
	"option\0"
	"optionally\0"
	"options\0"
	"or\0"
	"order\0"
	"out\0"
	"outer\0"
	"outfile\0"
	"output\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"owned\0"
	"owner\0"
	"package\0"
	"packages\0"
	"paglock\0"
	"parallel_enable\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"pctfree\0"
	"per\0"
	"percent\0"
	"performance\0"
	"perm\0"
	"persisted\0"
	"pipelined\0"
	"placing\0"
	"plan\0"
	"plans\0"
	"policy\0"
	"pool\0"
	"position\0"
	"precedes\0"
	"preceding\0"
	"precision\0"
	"predict\0"
	"preferred\0"
	"prefix\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"priorer\0"
	"private\0"
	"privilege\0"
	"privileges\0"
	"proc\0"
	"procedural\0"
	"procedure\0"
	"profile\0"
	"publication\0"
	"publish\0"
	"purge\0"
	"q\0"
	"qq\0"
	"quarter\0"
	"query\0"
	"quote\0"
	"randomized\0"
	"range\0"
	"ratio\0"
	"raw\0"
	"read\0"
	"readcommitted\0"
	"readpast\0"
	"readuncommitted\0"
	"real\0"
	"reassign\0"
	"rebuild\0"
	"recheck\0"
	"recursive\0"
	"recyclebin\0"
	"redisanyvalue\0"
	"ref\0"
	"references\0"
	"refresh\0"
	"reindex\0"
	"reject\0"
	"relative\0"
	"release\0"
	"reloptions\0"
	"remote\0"
	"remove\0"
	"rename\0"
	"repeat\0"
	"repeatable\0"
	"repeatableread\0"
	"replace\0"
	"replica\0"
	"reseed\0"
	"reset\0"
	"resize\0"
	"resource\0"
	"respect\0"
	"restart\0"
	"restrict\0"
	"result\0"
	"return\0"
	"returned_sqlstate\0"
	"returning\0"
	"returns\0"
	"reuse\0"
	"revoke\0"
	"right\0"
	"role\0"
	"roles\0"
	"rollback\0"
	"rollup\0"
	"rotate\0"
	"rotation\0"
	"row\0"
	"row_count\0"
	"rowlock\0"
	"rows\0"
	"rowtype\0"
	"rule\0"
	"s\0"
	"sample\0"
	"save\0"
	"savepoint\0"
	"schedule\0"
	"schema\0"
	"schema_name\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"self\0"
	"separator\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"share_memory\0"
	"shippable\0"
	"show\0"
	"shrink\0"
	"shutdown\0"
	"siblings\0"
	"similar\0"
	"simple\0"
	"size\0"
	"skip\0"
	"slave\0"
	"slice\0"
	"smalldatetime\0"
	"smalldatetime_format\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"source\0"
	"space\0"
	"specification\0"
	"spill\0"
	"split\0"
	"sql\0"
	"ss\0"
	"stable\0"
	"stacked\0"
	"standalone\0"
	"start\0"
	"starting\0"
	"starts\0"
	"statement\0"
	"statement_id\0"
	"static\0"
	"statistics\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"store\0"
	"stored\0"
	"stratify\0"
	"stream\0"
	"strict\0"
	"strip\0"
	"subclass_origin\0"
	"subpartition\0"
	"subpartitions\0"
	"subscription\0"
	"substring\0"
	"symmetric\0"
	"synonym\0"
	"sys_refcursor\0"
	"sysdate\0"
	"sysid\0"
	"system\0"
	"table\0"
	"table_name\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"tablock\0"
	"tablockx\0"
	"target\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"terminated\0"
	"text\0"
	"textimage_on\0"
	"than\0"
	"then\0"
	"ties\0"
	"time\0"
	"time_format\0"
	"timecapsule\0"
	"timestamp\0"
	"timestamp_format\0"
	"timestampdiff\0"
	"timezone_hour\0"
	"timezone_minute\0"
	"tinyint\0"
	"to\0"
	"top\0"
	"trailing\0"
	"tran\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"try\0"
	"try_cast\0"
	"try_convert\0"
	"tsfield\0"
	"tstag\0"
	"tstime\0"
	"type\0"
	"types\0"
	"unbounded\0"
	"uncommitted\0"
	"under\0"
	"unencrypted\0"
	"unimcstored\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlimited\0"
	"unlisten\0"
	"unlock\0"
	"unlogged\0"
	"until\0"
	"unusable\0"
	"update\0"
	"updlock\0"
	"use\0"
	"useeof\0"
	"user\0"
	"using\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validation\0"
	"validator\0"
	"value\0"
	"values\0"
	"varchar\0"
	"varchar2\0"
	"variables\0"
	"variadic\0"
	"varray\0"
	"varying\0"
	"vcgroup\0"
	"verbose\0"
	"verify\0"
	"version\0"
	"view\0"
	"visible\0"
	"volatile\0"
	"w\0"
	"wait\0"
	"warnings\0"
	"weak\0"
	"week\0"
	"weekday\0"
	"when\0"
	"where\0"
	"while\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"wk\0"
	"work\0"
	"workload\0"
	"wrapper\0"
	"write\0"
	"ww\0"
	"xact_abort\0"
	"xlock\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"y\0"
	"year\0"
	"year_month\0"
	"yes\0"
	"yy\0"
	"yyyy\0"
	"zone";

static const uint16 pgtsql_ScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	30,
	37,
	41,
	47,
	53,
	63,
	73,
	77,
	82,
	88,
	95,
	103,
	111,
	115,
	119,
	123,
	130,
	136,
	144,
	150,
	153,
	157,
	162,
	172,
	183,
	194,
	197,
	207,
	213,
	220,
	234,
	249,
	260,
	271,
	280,
	288,
	295,
	301,
	321,
	329,
	336,
	343,
	357,
	380,
	398,
	413,
	417,
	424,
	429,
	440,
	445,
	453,
	458,
	468,
	476,
	482,
	485,
	490,
	508,
	535,
	541,
	546,
	553,
	564,
	572,
	581,
	586,
	591,
	599,
	612,
	618,
	624,
	631,
	636,
	646,
	662,
	675,
	683,
	689,
	700,
	711,
	717,
	730,
	736,
	743,
	761,
	780,
	785,
	791,
	799,
	809,
	818,
	826,
	836,
	843,
	865,
	888,
	900,
	908,
	920,
	928,
	937,
	944,
	954,
	962,
	987,
	995,
	1004,
	1015,
	1024,
	1037,
	1047,
	1061,
	1069,
	1080,
	1091,
	1100,
	1111,
	1130,
	1146,
	1164,
	1176,
	1188,
	1196,
	1205,
	1214,
	1225,
	1233,
	1245,
	1258,
	1263,
	1268,
	1275,
	1281,
	1285,
	1289,
	1294,
	1302,
	1318,
	1331,
	1344,
	1359,
	1372,
	1390,
	1403,
	1410,
	1422,
	1428,
	1430,
	1435,
	1444,
	1453,
	1462,
	1472,
	1484,
	1489,
	1501,
	1510,
	1523,
	1527,
	1536,
	1547,
	1558,
	1568,
	1573,
	1589,
	1592,
	1603,
	1607,
	1615,
	1623,
	1630,
	1638,
	1647,
	1658,
	1667,
	1675,
	1682,
	1692,
	1703,
	1709,
	1720,
	1731,
	1736,
	1750,
	1762,
	1773,
	1780,
	1790,
	1798,
	1806,
	1817,
	1826,
	1837,
	1850,
	1853,
	1862,
	1869,
	1876,
	1881,
	1890,
	1900,
	1903,
	1906,
	1911,
	1919,
	1924,
	1931,
	1940,
	1949,
	1959,
	1975,
	1986,
	2002,
	2006,
	2011,
	2020,
	2025,
	2029,
	2035,
	2042,
	2049,
	2057,
	2066,
	2072,
	2079,
	2085,
	2092,
	2101,
	2109,
	2118,
	2128,
	2138,
	2143,
	2151,
	2158,
	2166,
	2174,
	2184,
	2193,
	2201,
	2207,
	2214,
	2219,
	2228,
	2235,
	2241,
	2248,
	2259,
	2279,
	2286,
	2293,
	2299,
	2305,
	2311,
	2317,
	2327,
	2335,
	2339,
	2345,
	2353,
	2363,
	2371,
	2378,
	2383,
	2388,
	2397,
	2407,
	2417,
	2421,
	2428,
	2434,
	2442,
	2451,
	2457,
	2466,
	2478,
	2486,
	2493,
	2507,
	2514,
	2517,
	2522,
	2527,
	2539,
	2551,
	2562,
	2571,
	2574,
	2581,
	2599,
	2605,
	2615,
	2625,
	2635,
	2644,
	2647,
	2655,
	2665,
	2675,
	2687,
	2693,
	2701,
	2708,
	2717,
	2725,
	2734,
	2742,
	2752,
	2761,
	2768,
	2774,
	2780,
	2786,
	2798,
	2805,
	2813,
	2817,
	2825,
	2834,
	2844,
	2853,
	2858,
	2868,
	2876,
	2879,
	2882,
	2889,
	2899,
	2904,
	2916,
	2921,
	2925,
	2934,
	2944,
	2949,
	2955,
	2964,
	2970,
	2975,
	2983,
	2994,
	3003,
	3011,
	3021,
	3027,
	3032,
	3037,
	3043,
	3048,
	3054,
	3060,
	3065,
	3072,
	3077,
	3083,
	3093,
	3108,
	3117,
	3122,
	3129,
	3133,
	3141,
	3151,
	3165,
	3179,
	3186,
	3191,
	3193,
	3197,
	3205,
	3213,
	3220,
	3226,
	3234,
	3247,
	3251,
	3262,
	3270,
	3279,
	3288,
	3292,
	3299,
	3305,
	3318,
	3325,
	3328,
	3340,
	3352,
	3363,
	3369,
	3376,
	3390,
	3398,
	3407,
	3410,
	3415,
	3421,
	3428,
	3434,
	3439,
	3448,
	3451,
	3463,
	3465,
	3470,
	3476,
	3480,
	3491,
	3500,
	3508,
	3514,
	3519,
	3522,
	3534,
	3545,
	3553,
	3558,
	3567,
	3574,
	3584,
	3595,
	3606,
	3619,
	3624,
	3633,
	3637,
	3645,
	3652,
	3660,
	3671,
	3678,
	3681,
	3691,
	3696,
	3705,
	3712,
	3718,
	3725,
	3733,
	3740,
	3749,
	3759,
	3763,
	3770,
	3773,
	3777,
	3784,
	3789,
	3792,
	3797,
	3806,
	3819,
	3826,
	3837,
	3845,
	3848,
	3854,
	3858,
	3864,
	3872,
	3879,
	3884,
	3893,
	3901,
	3907,
	3913,
	3921,
	3930,
	3938,
	3954,
	3961,
	3969,
	3979,
	3990,
	3998,
	4007,
	4015,
	4019,
	4027,
	4039,
	4044,
	4054,
	4064,
	4072,
	4077,
	4083,
	4090,
	4095,
	4104,
	4113,
	4123,
	4133,
	4141,
	4151,
	4158,
	4166,
	4175,
	4184,
	4192,
	4198,
	4206,
	4214,
	4224,
	4235,
	4240,
	4251,
	4261,
	4269,
	4281,
	4289,
	4295,
	4297,
	4300,
	4308,
	4314,
	4320,
	4331,
	4337,
	4343,
	4347,
	4352,
	4366,
	4375,
	4391,
	4396,
	4405,
	4413,
	4421,
	4431,
	4442,
	4456,
	4460,
	4471,
	4479,
	4487,
	4494,
	4503,
	4511,
	4522,
	4529,
	4536,
	4543,
	4550,
	4561,
	4576,
	4584,
	4592,
	4599,
	4605,
	4612,
	4621,
	4629,
	4637,
	4646,
	4653,
	4660,
	4678,
	4688,
	4696,
	4702,
	4709,
	4715,
	4720,
	4726,
	4735,
	4742,
	4749,
	4758,
	4762,
	4772,
	4780,
	4785,
	4793,
	4798,
	4800,
	4807,
	4812,
	4822,
	4831,
	4838,
	4850,
	4857,
	4864,
	4871,
	4880,
	4887,
	4892,
	4902,
	4911,
	4921,
	4934,
	4941,
	4949,
	4962,
	4966,
	4972,
	4977,
	4983,
	4996,
	5006,
	5011,
	5018,
	5027,
	5036,
	5044,
	5051,
	5056,
	5061,
	5067,
	5073,
	5087,
	5108,
	5117,
	5126,
	5131,
	5138,
	5144,
	5158,
	5164,
	5170,
	5174,
	5177,
	5184,
	5192,
	5203,
	5209,
	5218,
	5225,
	5235,
	5248,
	5255,
	5266,
	5272,
	5279,
	5287,
	5293,
	5300,
	5309,
	5316,
	5323,
	5329,
	5345,
	5358,
	5372,
	5385,
	5395,
	5405,
	5413,
	5427,
	5435,
	5441,
	5448,
	5454,
	5465,
	5472,
	5484,
	5495,
	5503,
	5512,
	5519,
	5524,
	5533,
	5543,
	5554,
	5559,
	5572,
	5577,
	5582,
	5587,
	5592,
	5604,
	5616,
	5626,
	5643,
	5657,
	5671,
	5687,
	5695,
	5698,
	5702,
	5711,
	5716,
	5728,
	5738,
	5744,
	5752,
	5757,
	5762,
	5771,
	5779,
	5783,
	5792,
	5804,
	5812,
	5818,
	5825,
	5830,
	5836,
	5846,
	5858,
	5864,
	5876,
	5888,
	5894,
	5901,
	5909,
	5919,
	5928,
	5935,
	5944,
	5950,
	5959,
	5966,
	5974,
	5978,
	5985,
	5990,
	5996,
	6003,
	6009,
	6018,
	6029,
	6039,
	6045,
	6052,
	6060,
	6069,
	6079,
	6088,
	6095,
	6103,
	6111,
	6119,
	6126,
	6134,
	6139,
	6147,
	6156,
	6158,
	6163,
	6172,
	6177,
	6182,
	6190,
	6195,
	6201,
	6207,
	6218,
	6225,
	6230,
	6237,
	6245,
	6248,
	6253,
	6262,
	6270,
	6276,
	6279,
	6290,
	6296,
	6300,
	6314,
	6324,
	6335,
	6345,
	6355,
	6364,
	6370,
	6378,
	6391,
	6393,
	6398,
	6409,
	6413,
	6416,
	6421,
};

#define PGTSQL_SCANKEYWORDS_NUM_KEYWORDS 781

static int
pgtsql_ScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1563] = {
		32767, 32767, 66,    0,     32767, 32767, 32767, 32767,
		-107,  32767, 594,   32767, 0,     780,   32767, -242,
		32767, 274,   32767, 722,   32767, 290,   32767, 575,
		-98,   0,     164,   32767, -43,   32767, 32767, 344,
		601,   474,   32767, 1779,  -351,  29,    32767, 373,
		442,   730,   32767, -570,  32767, 32767, 32767, -186,
		-222,  0,     0,     153,   -1809, 116,   0,     -1685,
		0,     47,    672,   32767, -583,  677,   -453,  32767,
		700,   504,   32767, 545,   121,   -95,   678,   32767,
		0,     0,     0,     -75,   335,   181,   382,   32767,
		541,   32767, 32767, 32767, 32767, 32767, -372,  -843,
		32767, 627,   539,   32767, 32767, 927,   519,   -66,
		32767, 660,   925,   408,   554,   685,   32767, 535,
		32767, 167,   32767, 32767, 32767, 816,   440,   396,
		0,     -388,  361,   582,   32767, 32767, -41,   742,
		32767, 460,   -222,  32767, 32767, 672,   32767, 32767,
		32767, 32767, 32767, 32767, 0,     32767, 318,   742,
		32767, 32767, 32767, -342,  0,     197,   -65,   139,
		32767, 32767, 32767, 884,   -1316, 177,   -108,  32767,
		32,    1487,  0,     32767, -7,    571,   710,   644,
		32767, 85,    32767, 32767, -128,  32767, 32767, 699,
		32767, 0,     314,   517,   32767, -123,  0,     63,
		265,   32767, 262,   32767, 383,   0,     -124,  32767,
		527,   -105,  32767, 270,   103,   32767, 32767, 168,
		536,   689,   570,   70,    266,   32767, 339,   32767,
		1157,  438,   -479,  56,    692,   -619,  0,     32767,
		32767, 559,   32767, 32767, 190,   454,   514,   -401,
		595,   141,   511,   262,   0,     32767, 269,   32767,
		69,    779,   421,   -403,  32767, 32767, 533,   32767,
		432,   32767, 32767, 906,   -445,  -33,   32767, 0,
		903,   -165,  -4,    175,   564,   32767, 0,     458,
		314,   2071,  211,   435,   -1,    32767, 32767, 0,
		487,   412,   32767, 1051,  392,   284,   32767, 629,
		32767, 45,    32767, -37,   510,   32767, -258,  -58,
		505,   -510,  -503,  169,   -156,  32767, 524,   32767,
		-172,  32767, 32767, 32767, 807,   -57,   205,   -219,
		32767, 32767, 184,   32767, 32767, 0,     594,   -585,
		0,     32767, 404,   483,   32767, 0,     420,   -628,
		0,     -961,  32767, 549,   0,     0,     0,     977,
		0,     32767, 0,     32767, -581,  32767, 40,    0,
		99,    32767, 418,   1994,  32767, 32767, 679,   32767,
		32767, 0,     163,   32767, 32767, 0,     -155,  543,
		622,   375,   0,     32767, 32767, 0,     246,   32767,
		32767, 479,   32767, -108,  0,     222,   -87,   32767,
		534,   32767, 32767, -195,  0,     1034,  0,     32767,
		32767, 0,     -69,   683,   348,   68,    -352,  302,
		62,    32767, 378,   32767, 112,   -173,  376,   499,
		525,   533,   0,     439,   0,     -138,  32767, 32767,
		0,     32767, 156,   0,     32767, 0,     457,   32767,
		32767, 325,   26,    32767, 32767, 32767, 283,   -71,
		423,   -375,  32767, 450,   32767, 32767, 32767, 293,
		32767, 289,   -1212, 125,   509,   32767, 32767, 32767,
		32767, 409,   110,   32767, 431,   32767, 32767, -439,
		497,   0,     133,   335,   32767, 374,   0,     32767,
		32767, 32767, 32767, -25,   1976,  32767, 631,   32767,
		32767, 729,   536,   32767, 32767, 32767, 0,     -357,
		32767, 556,   559,   32767, 32767, 0,     32767, -309,
		32767, 999,   549,   -610,  32767, 21,    156,   32767,
		32767, 32767, 106,   -38,   576,   0,     624,   36,
		65,    249,   -313,  32767, 0,     637,   698,   1353,
		32767, 718,   32767, -13,   19,    281,   32767, 0,
		611,   92,    32767, -1525, 32767, 457,   32767, 696,
		32767, 32767, -582,  -327,  -4,    84,    704,   706,
		32767, 0,     32767, 173,   542,   32767, 32767, 0,
		733,   -42,   0,     32767, 414,   0,     32767, 32767,
		533,   159,   32767, 32767, 900,   32767, 267,   32767,
		32767, 326,   419,   -61,   609,   137,   32767, 0,
		0,     32767, 224,   32767, 32767, 32767, 32767, 679,
		700,   652,   32767, 0,     32767, 32767, 320,   32767,
		32767, 32767, 894,   128,   32767, 32767, 32767, 150,
		202,   32767, -424,  32767, 468,   32767, -325,  857,
		83,    358,   32767, 32767, 1097,  32767, 32767, 32767,
		-224,  32767, 150,   -60,   32767, -194,  0,     32767,
		32767, 294,   -533,  32767, 0,     32767, 32767, 0,
		0,     1212,  32767, 397,   32767, 1042,  32767, 575,
		487,   46,    32767, 32767, 327,   827,   32767, 32767,
		86,    -450,  -494,  -6,    490,   345,   69,    32767,
		32767, 32767, 32767, 808,   -309,  32767, 32767, -11,
		32767, 0,     32767, 0,     32767, 0,     32767, -248,
		32767, -112,  32767, 32767, 32767, 247,   0,     -254,
		32767, 32767, 13,    286,   551,   32767, 400,   76,
		842,   32767, 0,     32767, 32767, 186,   784,   175,
		135,   516,   0,     32767, 32767, 32767, 164,   32767,
		349,   -9,    -97,   -714,  32767, 106,   32767, 299,
		452,   0,     471,   195,   32767, 1738,  32767, -776,
		183,   32767, 32767, 32767, -398,  318,   0,     0,
		312,   0,     -1149, 32767, 1107,  375,   32767, -419,
		32767, 32767, 32767, 343,   653,   0,     32767, -124,
		210,   32767, 32767, 32767, 32767, 54,    118,   32767,
		32767, 231,   182,   -258,  442,   -1502, 32767, 306,
		75,    32767, 32767, 153,   0,     331,   637,   270,
		21,    32767, 0,     0,     -755,  32767, 113,   32767,
		496,   298,   32767, 0,     401,   661,   615,   32767,
		-73,   32767, 32767, 738,   588,   440,   32767, 332,
		0,     32767, 0,     121,   -1227, 32767, 32767, 280,
		132,   0,     32767, 646,   130,   214,   32767, 642,
		249,   -12,   149,   32767, 470,   31,    372,   -433,
		633,   105,   643,   1293,  241,   32767, 623,   32767,
		32767, 776,   263,   745,   -24,   -468,  137,   767,
		507,   -239,  791,   -338,  32767, 1295,  -20,   0,
		0,     -615,  32767, 181,   32767, 707,   17,    32767,
		155,   779,   32767, 205,   32767, 268,   0,     32767,
		-62,   975,   -400,  455,   32767, 32767, 32767, 32767,
		32767, 453,   71,    527,   828,   32767, -79,   1,
		32767, 32767, 32767, 587,   491,   589,   266,   584,
		0,     32767, 107,   -82,   363,   32767, 65,    474,
		155,   258,   32767, 728,   32767, 234,   32767, -1881,
		568,   32767, 852,   -506,  32767, -83,   106,   580,
		-481,  -67,   32767, 0,     589,   32767, 32767, 1689,
		607,   32767, 32767, -372,  32767, 289,   221,   0,
		32767, 32767, -510,  -276,  632,   218,   0,     -128,
		32767, 32767, 213,   56,    0,     32767, 158,   -1147,
		-290,  -305,  15,    179,   51,    166,   0,     32767,
		154,   32767, 728,   32767, 32767, 32767, -126,  12,
		596,   304,   554,   0,     39,    32767, 636,   377,
		-56,   0,     -509,  32767, 366,   0,     466,   32767,
		-49,   32767, -221,  -49,   32767, 632,   32767, 32767,
		25,    966,   32767, 32767, 32767, 32767, 119,   -90,
		650,   -105,  32767, 817,   121,   49,    32767, -279,
		656,   0,     32767, 0,     238,   289,   -522,  163,
		477,   32767, 0,     -632,  -62,   32767, 0,     32767,
		32767, 32767, 32767, 32767, 346,   569,   32767, 842,
		32767, 463,   32767, 28,    183,   32767, -39,   0,
		661,   32767, 32767, 32767, -446,  1012,  394,   731,
		-464,  129,   0,     421,   32767, 32767, 0,     -866,
		0,     32767, 693,   33,    32767, 76,    374,   -280,
		173,   32767, 32767, 0,     32767, 0,     -1022, 0,
		0,     -360,  419,   324,   806,   32767, 32767, 32767,
		1074,  493,   0,     643,   106,   32767, 1583,  362,
		32767, 32767, 367,   32767, 665,   32767, 0,     32767,
		0,     32767, -39,   568,   620,   32767, 32767, 0,
		0,     706,   32767, 0,     820,   -544,  32767, 82,
		32767, 32767, 32767, 32767, 32767, 547,   0,     32767,
		38,    621,   32767, 0,     32767, 32767, -708,  32767,
		-625,  666,   664,   940,   32767, 388,   178,   32767,
		-76,   32767, 58,    32767, 504,   176,   32767, 32767,
		0,     32767, 1060,  0,     32767, 0,     333,   -121,
		0,     0,     0,     -150,  458,   32767, 0,     0,
		0,     0,     32767, -79,   32767, 580,   445,   25,
		-254,  0,     0,     -81,   32767, 32767, 0,     -1023,
		32767, 0,     312,   32767, 607,   483,   323,   525,
		32767, -1019, 32767, 0,     32767, 70,    32767, 32767,
		431,   176,   32767, 32767, 32767, 0,     137,   694,
		160,   0,     408,   32767, -208,  85,    32767, 2402,
		0,     192,   1326,  0,     321,   32767, 0,     53,
		244,   -1226, 32767, 32767, 0,     -11,   32767, 0,
		0,     645,   32767, 32767, 633,   32767, 205,   102,
		0,     32767, 32767, 551,   32767, 1716,  233,   0,
		-511,  32767, 32767, 32767, 32767, 32767, 32767, 32767,
		134,   0,     278,   750,   227,   0,     32767, 32767,
		32767, 0,     277,   32767, 32767, 538,   32767, 32767,
		32767, 747,   60,    0,     32767, 88,    248,   0,
		-3,    38,    433,   497,   466,   299,   619,   -207,
		32767, 189,   -460,  122,   680,   204,   104,   32767,
		140,   150,   0,     0,     32767, 32767, -273,  217,
		743,   0,     430,   -132,  43,    196,   32767, 32767,
		-142,  32767, 276,   386,   678,   738,   -66,   591,
		0,     32767, 438,   0,     32767, 32767, 208,   1257,
		32767, 32767, 0,     162,   422,   0,     32767, 0,
		32767, 549,   0,     261,   32767, 32767, -241,  0,
		66,    0,     413,   223,   32767, 32767, 665,   32767,
		32767, -636,  0,     0,     -201,  0,     0,     32767,
		628,   -1037, 626,   32767, 0,     -82,   32767, -258,
		0,     32767, 32767, 0,     32767, -192,  406,   32767,
		282,   125,   32767, 32767, 32767, 631,   32767, -645,
		32767, 32767, 32767, 32767, 32767, 13,    815,   460,
		454,   32767, 32767, 32767, 32767, 0,     32767, -164,
		32767, 32767, 666,   32767, 0,     32767, 0,     32767,
		318,   32767, 0,     0,     32767, 32767, 32767, 656,
		413,   32767, 32767, 32767, 32767, 32767, 48,    806,
		32767, 0,     721,   772,   0,     0,     32767, 32767,
		32767, 561,   32767, -1022, 0,     32767, 546,   283,
		0,     32767, 32767, 414,   32767, 32767, 0,     0,
		333,   0,     485,   32767, 32767, 403,   0,     0,
		0,     32767, 359,   0,     32767, 32767, 32767, 526,
		0,     32767, 32767, 281,   -990,  348,   32767, 94,
		32767, 32767, -166,  0,     27,    1342,  32767, 32767,
		257,   32767, 0,     0,     32767, 32767, 687,   32767,
		259,   716,   0,     129,   0,     32767, 0,     280,
		-123,  185,   32767, 482,   0,     730,   0,     32767,
		-601,  0,     61,    270,   237,   3,     32767, 619,
		701,   32767, -79,   -124,  235,   32767, 612,   0,
		167,   971,   -342,  32767, 526,   32767, 0,     1354,
		340,   32767, 32767, -83,   0,     32767, 32767, 32767,
		32767, 0,     117,   32767, 32767, 32767, 571,   326,
		32767, 32767, 0,     32767, 445,   -227,  32767, 32767,
		0,     32767, 302,   0,     32767, 0,     0,     32767,
		32767, 322,   751,   0,     548,   0,     0,     32767,
		32767, 653,   0,     332,   32767, 32767, 533,   32767,
		4,     32767, 32767, 0,     32767, -5,    32767, 32767,
		32767, -256,  510,   32767, 32767, 0,     0,     634,
		1215,  0,     32767, -9,    120,   240,   0,     0,
		625,   669,   0,     0,     32767, 0,     275,   32767,
		0,     0,     32767, 389,   0,     32767, 187,   398,
		253,   334,   319,   32767, 32767, -52,   509,   -451,
		0,     668,   632
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 1;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 1563] + h[b % 1563];
}

const ScanKeywordList pgtsql_ScanKeywords = {
	pgtsql_ScanKeywords_kw_string,
	pgtsql_ScanKeywords_kw_offsets,
	pgtsql_ScanKeywords_hash_func,
	PGTSQL_SCANKEYWORDS_NUM_KEYWORDS,
	26
};

#endif							/* KWLIST_D_H */
